In [30]:
import numpy as np

In [31]:
class Perceptron(object):
    """Implements a perceptron network"""
    def __init__(self, input_size, lr=1, epochs=100):
        self.W = np.zeros(input_size+1)
        # add one for bias
        self.epochs = epochs
        self.lr = lr
    
    def activation_fn(self, x):
        #return (x >= 0).astype(np.float32)
        return 1 if x >= 0 else 0
 
    def predict(self, x):
        x = np.insert(x,0,1)
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a
 
    def fit(self,X,d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                y = self.predict(X[i])
                e = d[i] - y
                self.W = self.W + self.lr * e * np.insert(X[i], 0, 1)

In [32]:
X = np.array([
        [0,0],
        [0,1],
        [1,0],
        [1,1]
            ])

In [33]:
d = np.array([0,0,0,1])

In [34]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [35]:
d

array([0, 0, 0, 1])

In [36]:
perceptron = Perceptron(input_size = 2)

In [37]:
perceptron.W

array([0., 0., 0.])

In [38]:
perceptron.fit(X,d)

In [39]:
perceptron.W

array([-3.,  2.,  1.])

In [40]:
print(perceptron.W)

[-3.  2.  1.]


In [41]:
perceptron.predict(np.asarray([0,0]))

0

In [42]:
mp = Perceptron(5)
x = np.asarray([1,1,0,0,0])
mp.predict(x)

1

In [43]:
mp.activation_fn(10)

1

In [44]:
mp.W

array([0., 0., 0., 0., 0., 0.])

In [46]:
# SORULAR

# 1) Perceptron class tanımınında var olan fonksiyonları kısaca tanıtınız.
 
"""    init fonksiyonu: 
       Perceptron objesini constructure olarak oluşturmamızı sağlar. Parametre olarak aldığı input size
       girilen veri sayısını ifade eder. Weight vektörünü oluşturmak için kaç tane veri girildiğini bilmemiz gerekir.
       Girilen veri sayısına +1 eklememizin sebebi weight vektörüne sapmayı dahil etmektir.
  
       activation fonksiyonu: 
       Perceptron işleminde sondaki değeri döndürür. Bu fonksiyonda girilen input 0'dan büyük veya eşit ise 1,
       küçük ise 0 döndürür.

       predict fonksiyonu: 
       Perceptron ile bir input'u çalıştırmak ve bir output döndürmek için bu fonksiyona ihtiyaç vardır.
       Eğilimi input vektörüne ekledikten sonra iç çarpım hesaplanır. Sonrasında aktivasyon fonksiyonu kullanabiliriz.
 
       fit fonksiyonu: 
       X ile d'yi parametre alarak weight (w) değerlerinin incelenmesini sağlar.
"""

In [47]:
# 2) XOR için verileri değiştirip çalışmasınızı gözlemleyiniz.  

X = np.array([
        [0,0],
        [0,1],
        [1,0],
        [1,1]
            ])
d = np.array([0,1,1,0])

In [48]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [49]:
d

array([0, 1, 1, 0])

In [50]:
perceptron = Perceptron(input_size = 2)
perceptron.W

array([0., 0., 0.])

In [52]:
perceptron.fit(X,d)
perceptron.W

array([ 0., -1.,  0.])

In [58]:
# Denemeler

perceptron.predict(np.asarray([0,0]))

1

In [55]:
perceptron.predict(np.asarray([1,0]))

0

In [56]:
perceptron.predict(np.asarray([0,1]))

1

In [57]:
perceptron.predict(np.asarray([1,1]))

0

In [ ]:
# 3) Bu class ile dersimize kayıtlı 40 öğrenci için imza tanıması yapılırsa X ve d değerlerini ne olur, predict fonksiyonu nasıl kullanılır açıklayınız.

"""  X -> input
     d -> output
     
     Derse kayıtlı 40 öğrenci için imza tanıması yapılırsa buradaki X -> 40 tane imzanın oluşturduğu dizileri tutacaktır.
     d -> 40 tane değere sahip bir dizidir. Bu değerlerin her birinin karşılığı bir öğrenciye aittir.
     Predict fonksiyonu sayesinde öğrencilerin imzaları input olarak alınarak birtakım işlemler yapılır.
     İşlemler sonucunda çıkan output imzanın hangi öğrenciye ait olduğudur.
"""

# 4) Bu modelin hatası nasıl elde edilir, kendi çözümünüzü/yorumunuzu yazınız.

"""  e = d - y formülü ile elde edebiliriz. Çıkmasını istenen değerden (d) öngördüğümüz değeri (y) çıkararak hatayı
     tanımlayabiliriz. d ve y değerleri aynıysa hata değeri 0 değerine karşılık gelecektir, bu durumda weight vektörünü
     değiştirmemize gerek kalmaz. Fakat d ve y'nin 0,1 veya 1,0 olması durumunda hata değeri -1 veya 1 değerini alacaktır,
     bu sebeple weight vektörünü güncellemiz gerekir.

"""